### ISSUE TITLE
DBT engines to support

### ISSUE THREAD

**Issue by crericha** [TobikoData/sqlmesh#254]
- [x] Snowflake (additional authentication methods)
  - [ ] BigQuery (converted to issue #573)
  - [x] Redshift
  - [ ] Spark (converted to issue #575)
  - [x] Databricks
  - [ ] Presto/Trino (converted to issue #574 )
  - [x] Duckdb
