### ISSUE TITLE
DBT config todo

### ISSUE THREAD

**Issue by crericha** [TobikoData/sqlmesh#72]
- [x] Get source config
- [ ] Get data warehouse connection config for
  - [x] Snowflake (additional authentication methods)
  - [ ] BigQuery
  - [x] Redshift
  - [ ] Spark
  - [x] Databricks
  - [ ] Presto/Trino
  - [ ] Duckdb
- [x] Support undefined fields in model config (e.g. time_column field)
- [x] Support environment variables 
  - [x] For configuration location (profiles.yml, dbt_project.yml, etc.)
  - [x] Embedded in jinja within yml files
- [x] Support configurable model folder location in dbt_project.yml
- [x] Break-out general config from model config into base class that can be used by seeds
- [ ] Get project vars within dbt_project.yml
- [x] Get Model columns config
- [x] Get seeds
- [ ] Get DBT tests (aka audits)
- [ ] Support packages
